import Head from "next/head";
import Image from "next/image";
import styles from "../src/styles/Home.module.css";
import Header from "../src/components/header/Header";
import Home from "../src/components/home/Home";
import About from "../src/components/about/About";
import Skills from "../src/components/skills/Skills";
import Services from "../src/components/services/Services";
import Qualification from "../src/components/qualification/Qualification";
import Contact from "../src/components/contact/Contact";
import Footer from "../src/components/footer/Footer";
import ScrollUp from "../src/components/scrollup/ScrollUp";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Enzo&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="main">
        <Home />
        <About />
        <Skills />
        <Services />
        <Qualification />
        <Contact />
      </main>

      <Footer />
      <ScrollUp />
    </div>
  );
}
