import Head from 'next/head'
import Image from 'next/image'
import styles from '../src/styles/Home.module.css'
import Header from "../src/components/header/Header";
import Home from "../src/components/home/Home";
import About from "../src/components/about/About";
import Skills from "../src/components/skills/Skills";
import Services from "../src/components/services/Services";
export default function Index() {
    return (
        <div >
            <Head>
                <title>Enzo&apos;s Portfolio</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
                <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"/>
            </Head>

            <>
                <Header></Header>
                <main className="main">
                    {/* add sections here*/}
                    <Home/>
                    <About/>
                    <Skills/>
                    <Services/>
                </main>
            </>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}
